name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-all:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v6

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js 22.x
        uses: actions/setup-node@v5
        with:
          node-version: 22.x
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --immutable --check-cache --check-resolutions

      - name: Check yarn dedupe
        run: yarn dedupe --check

      - name: Run all
        run: yarn  run all

      - name: Verify dist is up-to-date
        run: git diff --name-only --exit-code -- dist

  validate-typings:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v6

      - name: Validate typings
        uses: typesafegithub/github-actions-typing@v2
