name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  validate-typings:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v6

      - uses: typesafegithub/github-actions-typing@v2
