name: Security checks
on:
  pull_request:
    paths:
      - package.json
      - bun.lock
      - bunfig.toml
  push:
    branches:
      - master

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v6

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Run Bun audit
        run: bun audit --audit-level=moderate
